// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBODd4evpwEl9OEi7AAhnSGmRKgxMvAinc',
    appId: '1:335387513443:web:04ce24840fbe08741b9e56',
    messagingSenderId: '335387513443',
    projectId: 'social-vape',
    authDomain: 'social-vape.firebaseapp.com',
    databaseURL: 'https://social-vape-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'social-vape.appspot.com',
    measurementId: 'G-Y5NJ1JV9RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrpl9gX9_sn_0Z-mXZw9f0n0nIkbo55A',
    appId: '1:335387513443:android:fbdb01778a7ad8c51b9e56',
    messagingSenderId: '335387513443',
    projectId: 'social-vape',
    databaseURL: 'https://social-vape-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'social-vape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeOYC7jzxqarabjzEiVdB2RU4DXuuAYm4',
    appId: '1:335387513443:ios:218d66bcdc52f5b31b9e56',
    messagingSenderId: '335387513443',
    projectId: 'social-vape',
    databaseURL: 'https://social-vape-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'social-vape.appspot.com',
    androidClientId: '335387513443-223t7m6lqncvcdlp46gujqsjpsnufee9.apps.googleusercontent.com',
    iosClientId: '335387513443-gsalvq9tshuikoa48d63iqj7sgdaa7k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialVape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeOYC7jzxqarabjzEiVdB2RU4DXuuAYm4',
    appId: '1:335387513443:ios:218d66bcdc52f5b31b9e56',
    messagingSenderId: '335387513443',
    projectId: 'social-vape',
    databaseURL: 'https://social-vape-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'social-vape.appspot.com',
    androidClientId: '335387513443-223t7m6lqncvcdlp46gujqsjpsnufee9.apps.googleusercontent.com',
    iosClientId: '335387513443-gsalvq9tshuikoa48d63iqj7sgdaa7k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialVape',
  );
}
